// Author the pre-baked fallback lines (src/content/data/fallbackLines.json).
//
// Fallbacks must ALWAYS validate. We generate them with our own pipeline using simple,
// known-good configs (low difficulty, no accidentals, the classic open position) and
// allowFallback DISABLED, scanning seeds until each bar count produces a clean line.
// The resulting Line objects are serialized to JSON. Re-run after generator changes:
//
//   npx tsx scripts/authorFallbacks.ts
//
// This is a build-time tool (NOT a pure module): it uses Node fs to write the JSON.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { generateLine } from '../src/generator/generateLine.js';
import type { LineConfig } from '../src/generator/config.js';
import { FOUR_FOUR, makeNeckPosition } from '../src/domain/index.js';
import type { Line } from '../src/domain/index.js';

// A deliberately boring, safe config: C major, open position, easiest difficulty, no
// chromaticism. The generator handles these cleanly within a few attempts.
function safeConfig(barCount: number): LineConfig {
  return {
    key: { tonic: { name: 'C', accidental: 'natural' }, mode: 'major' },
    timeSignature: FOUR_FOUR,
    position: makeNeckPosition(1, 6, 0, 5, 'open'),
    tempo: 80,
    barCount,
    difficulty: 1,
    accidentalsDensity: 'none',
  };
}

// Fixed timestamp so fallback authoring is itself reproducible (the generator forbids
// reading the system clock).
const FIXED_AT = '2026-01-01T00:00:00.000Z';

/** Find the first seed that yields a clean (non-fallback) line for this config. */
function firstCleanLine(config: LineConfig): Line {
  for (let seed = 1; seed < 5000; seed++) {
    try {
      // allowFallback:false makes a non-validating result throw instead of substituting.
      return generateLine(config, seed, FIXED_AT, { allowFallback: false });
    } catch {
      // This seed exhausted retries; try the next one.
      continue;
    }
  }
  throw new Error(
    `[GEN] could not author a clean fallback for barCount ${config.barCount}`,
  );
}

function main(): void {
  const barCounts = [2, 4];
  const lines: Line[] = barCounts.map((bc) => firstCleanLine(safeConfig(bc)));

  const doc = {
    _meta: {
      PLACEHOLDER: true,
      note:
        'Pre-authored safe fallback lines, GENERATED by scripts/authorFallbacks.ts ' +
        'from boring known-good configs (C major, open position, difficulty 1, no ' +
        'accidentals). They always validate. Regenerate after generator changes via: ' +
        'npx tsx scripts/authorFallbacks.ts',
      schemaVersion: 1,
      generatedAt: FIXED_AT,
    },
    lines,
  };

  const out = resolve(
    import.meta.dirname,
    '../src/content/data/fallbackLines.json',
  );
  writeFileSync(out, JSON.stringify(doc, null, 2) + '\n', 'utf8');
  console.log(
    `[GEN] wrote ${lines.length} fallback lines (barCounts ${barCounts.join(', ')}) to ${out}`,
  );
}

main();
